# Generated by Django 5.0 on 2024-04-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slmsapp', '0006_staff_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_leave',
            name='parent_phone',
            field=models.CharField(default=122222222223, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff_leave',
            name='student_phone',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'staff')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='staff_leave',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
