# Generated by Django 5.0 on 2024-04-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slmsapp', '0007_staff_leave_parent_phone_staff_leave_student_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='gender',
            new_name='Department',
        ),
        migrations.AddField(
            model_name='staff_leave',
            name='proof',
            field=models.ImageField(default=1234567, upload_to='media/proof'),
            preserve_default=False,
        ),
    ]
