# Generated by Django 5.0 on 2024-04-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slmsapp', '0008_rename_gender_staff_department_staff_leave_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_leave',
            name='parent_phone',
        ),
        migrations.RemoveField(
            model_name='staff_leave',
            name='student_phone',
        ),
        migrations.AddField(
            model_name='staff',
            name='parent_phone',
            field=models.CharField(default=11, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='student_phone',
            field=models.CharField(default=111, max_length=20),
            preserve_default=False,
        ),
    ]
