# Generated by Django 5.0 on 2024-04-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slmsapp', '0009_remove_staff_leave_parent_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='floor_incharge',
            field=models.CharField(default=111, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'staff'), (1, 'admin')], default=1, max_length=50),
        ),
    ]
