# Generated by Django 5.0 on 2024-04-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slmsapp', '0010_staff_floor_incharge_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='TimeTable',
            field=models.ImageField(default=1, upload_to='media/timetable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'staff')], default=1, max_length=50),
        ),
    ]
