# Generated by Django 5.0 on 2024-04-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slmsapp', '0011_remove_staff_leave_floor_incharge_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='room_bed_number',
            field=models.CharField(max_length=50),
        ),
    ]
