# Generated by Django 5.0 on 2024-04-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slmsapp', '0011_staff_timetable_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_leave',
            name='room_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
