# Generated by Django 5.0 on 2024-05-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slmsapp', '0011_staff_timetable_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='floor_incharge_phone',
            field=models.CharField(default=12345678, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='room_number',
            field=models.CharField(default=11, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'staff'), (1, 'admin')], default=1, max_length=50),
        ),
    ]
