# Generated by Django 5.0 on 2024-04-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slmsapp', '0017_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='floor_incharge_name',
        ),
    ]
