# Generated by Django 5.0 on 2024-04-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slmsapp', '0018_remove_staff_floor_incharge_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='room_bed_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'staff')], default=1, max_length=50),
        ),
    ]
